

386_OBJECTS=\
 $(OBJ_PATH)\$O\busenum.obj \
 $(OBJ_PATH)\$O\pnp.obj \
 $(OBJ_PATH)\$O\power.obj \
 $(OBJ_PATH)\$O\buspdo.obj \
 $(OBJ_PATH)\$O\wmi.obj \


_RES_FILE=$(OBJ_PATH)\$O\busenum.res



# lowercased
BASEDIR=e:\winddk\7600.16385.1
OBJECT_ROOT=e:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=c:\users\lenovo\desktop\bluescreen\usbip-windows-master\trunk\driver
OBJ_PATH=c:\users\lenovo\desktop\bluescreen\usbip-windows-master\trunk\driver
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
